name: pubdev

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: sakebook/actions-flutter-pub-publisher@v1.3.1
        name: "Publish to pub.dev"
        with:
          credential: ${{ secrets.PUBDEV_CREDENTIAL_JSON }}
          flutter_package: false
          skip_test: true
          dry_run: true
