name: release

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  github-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Determine if prerelease"
        id: check-prerelease
        run: |
          RELEASE_TAG=${GITHUB_REF#refs/tags/}
          if [[ "${RELEASE_TAG}" =~ "v.*-.*" ]]; then
             IS_PRERELEASE="true"
          else
             IS_PRERELEASE="false"
          fi

          echo "::set-output name=is-prerelease::${IS_PRERELEASE}"

      - uses: softprops/action-gh-release@v1
        with:
          prerelease: ${{ steps.check-prerelease.outputs.is-prerelease }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  pubdev-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1

      - name: "Install credentials file"
        run: |
          mkdir -p ~/.pub-cache
          echo "${{ secrets.PUBDEV_CREDENTIAL_JSON_B64 }}" \
            | base64 --decode > ~/.pub-cache/credentials.json

      - name: "Publish to pub.dev"
        run: dart pub publish
